# Generated by Django 4.2.5 on 2023-09-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surename', models.CharField(max_length=100)),
                ('eye_color', models.CharField(max_length=50)),
                ('eye_length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('eye_astigmatism', models.BooleanField(default=False)),
                ('body_response', models.TextField()),
                ('signs_traffic', models.PositiveIntegerField()),
                ('lines_traffic', models.PositiveIntegerField()),
                ('give_way', models.PositiveIntegerField()),
                ('status_work', models.CharField(max_length=100)),
            ],
        ),
    ]
