# Generated by Django 4.2.5 on 2023-09-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alldata',
            name='body_response',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alldata',
            name='eye_astigmatism',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alldata',
            name='eye_length',
            field=models.CharField(max_length=100),
        ),
    ]
