# Generated by Django 4.2.5 on 2023-09-21 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0004_rename_leavelists_leavelist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Leavelist',
            new_name='Leavelists',
        ),
    ]
