# Generated by Django 4.2.5 on 2023-09-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0006_rename_leavelists_leavelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavelist',
            name='del_flg',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
